# Generated by Django 2.1.2 on 2018-12-03 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181203_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('url', models.CharField(max_length=1024, verbose_name='url')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='links', to='articles.Category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'useful url',
                'verbose_name_plural': 'useful urls',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.Category', verbose_name='category'),
        ),
    ]
