# Generated by Django 2.1.2 on 2018-12-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181203_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefullink',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='name'),
        ),
    ]
